-- NEXUS FREE v7.4 — SELF-CONTAINED
-- Build: 2026-02-26 14:53:53
-- Build ID: 36ae3bc8057b
-- By: Ryu & Cuakcer — #FREEWALTERSANCHEZ
-- ALL-IN-ONE — NO LOADSTRING, NO EXTERNAL URLS
-- Generated by builder.py — DO NOT EDIT MANUALLY

local _BUILD_VERSION = "7.4"
local _BUILD_ID = "36ae3bc8057b"
local _BUILD_BRAND = "NEXUS FREE"

-- ============================================
-- ANTI-HOOK BOOTSTRAP — Pre-boot critical function snapshot
-- Captures C-closure references BEFORE any hooks can be installed.
-- All security checks use these snapshots, not live globals.
-- ============================================
local _SAFE = {}
do
    -- Snapshot core functions at load time (unhookable — first to execute)
    _SAFE.pcall    = pcall
    _SAFE.type     = type
    _SAFE.tostring = tostring
    _SAFE.tonumber = tonumber
    _SAFE.rawget   = rawget
    _SAFE.rawset   = rawset
    _SAFE.select   = select
    _SAFE.pairs    = pairs
    _SAFE.ipairs   = ipairs
    _SAFE.next     = next
    _SAFE.unpack   = unpack or table.unpack
    _SAFE.error    = error
    _SAFE.setmetatable = setmetatable
    _SAFE.getmetatable = getmetatable
    _SAFE.require  = require

    -- String library snapshots
    _SAFE.string_sub    = string.sub
    _SAFE.string_byte   = string.byte
    _SAFE.string_char   = string.char
    _SAFE.string_format = string.format
    _SAFE.string_len    = string.len
    _SAFE.string_find   = string.find
    _SAFE.string_rep    = string.rep
    _SAFE.string_lower  = string.lower
    _SAFE.string_upper  = string.upper
    _SAFE.string_gsub   = string.gsub
    _SAFE.string_match  = string.match
    _SAFE.string_gmatch = string.gmatch

    -- Math library snapshots
    _SAFE.math_floor  = math.floor
    _SAFE.math_random = math.random
    _SAFE.math_abs    = math.abs
    _SAFE.math_max    = math.max
    _SAFE.math_min    = math.min
    _SAFE.math_huge   = math.huge

    -- OS library snapshots
    _SAFE.os_time  = os.time
    _SAFE.os_clock = os.clock

    -- Table library snapshots
    _SAFE.table_insert = table.insert
    _SAFE.table_remove = table.remove
    _SAFE.table_concat = table.concat
    _SAFE.table_sort   = table.sort

    -- Task library snapshots
    _SAFE.task_spawn = task.spawn
    _SAFE.task_wait  = task.wait
    _SAFE.task_defer = task.defer
    _SAFE.task_delay = task.delay

    -- Roblox service snapshots (anti-spoof)
    _SAFE.game = game
    _SAFE.workspace = workspace

    -- Executor API snapshots (if available)
    _SAFE.pcall(function()
        if getgenv then _SAFE.getgenv = getgenv end
        if iscclosure then _SAFE.iscclosure = iscclosure end
        if islclosure then _SAFE.islclosure = islclosure end
        if getrawmetatable then _SAFE.getrawmetatable = getrawmetatable end
        if hookfunction then _SAFE.hookfunction = hookfunction end
        if newcclosure then _SAFE.newcclosure = newcclosure end
    end)

    -- Verify bootstrap integrity: core funcs must be C-closures
    local _bootClean = true
    _SAFE.pcall(function()
        if _SAFE.iscclosure then
            local criticals = {
                _SAFE.pcall, _SAFE.type, _SAFE.tostring, _SAFE.rawget,
                _SAFE.pairs, _SAFE.ipairs, _SAFE.next, _SAFE.select,
            }
            for _, fn in _SAFE.ipairs(criticals) do
                if not _SAFE.iscclosure(fn) then
                    _bootClean = false
                end
            end
        end
    end)

    if not _bootClean then
        warn("[Nexus] [!] Anti-hook bootstrap: hooks detected at load time!")
    end

    -- Expose for all modules
    if _SAFE.getgenv then
        _SAFE.getgenv()._SAFE = _SAFE
    end
end


local _MODULE_HASHES = {
    ["auth"] = "c0f3e36203d0d0ef",
    ["config"] = "7370ab45e28aca46",
    ["main"] = "5da4ec19e7c28208",
    ["security"] = "c9e5ad457a0a1584",
    ["ui"] = "a218d189e9e7189b",
    ["utils"] = "d46572fe53b674e6",
}

local _modules = {}

_modules["security"] = function()
    -- Module: security | SHA: c9e5ad457a0a1584
    --[[
        Nexus Security Module v6.6 — ANTI-HOOK / ANTI-TAMPER
        Centralized security for free script distribution.
        Function integrity, environment checks, metamethod detection,
        heartbeat integrity, silent degrade
        NEXUS FREE — #FREEWALTERSANCHEZ
    ]]
    
    local Security = {}
    local Utils = nil
    
    -- Services
    local HttpService = game:GetService("HttpService")
    local Players = game:GetService("Players")
    
    -- Internal state
    local _violations = {}
    local _violationCount = 0
    local _degraded = false
    local _scanCount = 0
    
    -- ============================================
    -- STRING OBFUSCATION
    -- ============================================
    local function _s(bytes)
        local chars = {}
        for i = 1, #bytes do
            chars[i] = string.char(bytes[i])
        end
        return table.concat(chars)
    end
    
    local _STR = {
        request      = _s({ 114, 101, 113, 117, 101, 115, 116 }),
        http_request = _s({ 104, 116, 116, 112, 95, 114, 101, 113, 117, 101, 115, 116 }),
        namecall     = _s({ 95, 95, 110, 97, 109, 101, 99, 97, 108, 108 }),
        index        = _s({ 95, 95, 105, 110, 100, 101, 120 }),
        C_source     = _s({ 91, 67, 93 }),
    }
    
    -- ============================================
    -- FUNCTION INTEGRITY CHECKS
    -- ============================================
    
    local function _isHooked(func)
        if type(func) ~= "function" then return true end
        if iscclosure and not iscclosure(func) then return true end
        if islclosure and islclosure(func) then return true end
        if debug and debug.info then
            local s, source = pcall(debug.info, func, "s")
            if s and source and source ~= _STR.C_source then return true end
        end
        return false
    end
    
    local function _getCriticalFunctions()
        -- ANTI-HOOK: Direct global references — NEVER use getfenv (poisonable)
        local criticals = {}
    
        local checks = {
            { pcall,    "pcall" },
            { type,     "type" },
            { tostring, "tostring" },
            { rawget,   "rawget" },
            { rawset,   "rawset" },
        }
    
        for _, item in ipairs(checks) do
            if item[1] then table.insert(criticals, item) end
        end
    
        if string then
            if string.sub then table.insert(criticals, { string.sub, "string.sub" }) end
            if string.byte then table.insert(criticals, { string.byte, "string.byte" }) end
        end
    
        if os and os.time then
            table.insert(criticals, { os.time, "os.time" })
        end
    
        pcall(function()
            table.insert(criticals, { HttpService.JSONEncode, "HttpService.JSONEncode" })
            table.insert(criticals, { HttpService.JSONDecode, "HttpService.JSONDecode" })
        end)
    
        pcall(function()
            if getgenv then
                local genv = getgenv()
                local reqFunc = genv[_STR.request] or genv[_STR.http_request]
                if reqFunc then table.insert(criticals, { reqFunc, "NetworkHandler" }) end
            end
        end)
    
        return criticals
    end
    
    function Security.checkFunctionIntegrity()
        local violations = {}
        local criticals = _getCriticalFunctions()
    
        for _, item in ipairs(criticals) do
            if item[1] and _isHooked(item[1]) then
                table.insert(violations, item[2])
            end
        end
    
        return #violations == 0, violations
    end
    
    function Security.verifyFunction(func, name)
        if not func then return false end
        if _isHooked(func) then
            Security._recordViolation("hooked_function", name or "unknown")
            return false
        end
        return true
    end
    
    -- ============================================
    -- METAMETHOD TAMPER DETECTION
    -- ============================================
    
    function Security._checkMetamethods()
        local clean = true
        pcall(function()
            if not getrawmetatable then return end
            local gameMt = getrawmetatable(game)
            if gameMt then
                local ncHook = rawget(gameMt, _STR.namecall)
                if ncHook and islclosure and islclosure(ncHook) then
                    clean = false
                end
            end
        end)
        return clean
    end
    
    -- ============================================
    -- VIOLATION TRACKING
    -- ============================================
    
    function Security._recordViolation(category, detail)
        _violationCount = _violationCount + 1
        table.insert(_violations, {
            category = category,
            detail = detail or "",
            time = os.time(),
        })
    end
    
    function Security.getViolationCount()
        return _violationCount
    end
    
    function Security.isDegraded()
        return _degraded
    end
    
    local function _silentDegrade(reason)
        if _degraded then return end
        _degraded = true
    
        task.spawn(function()
            task.wait(math.random(10, 30))
            pcall(function()
                if getgenv then
                    local env = getgenv()
                    env.NexusShuttingDown = true
                end
            end)
        end)
    end
    
    -- ============================================
    -- FULL SCAN
    -- ============================================
    
    function Security.runFullScan()
        _scanCount = _scanCount + 1
        local allClean = true
        local reasons = {}
    
        local funcOk, funcViolations = Security.checkFunctionIntegrity()
        if not funcOk then
            allClean = false
            for _, v in ipairs(funcViolations) do
                Security._recordViolation("function_hooked", v)
                table.insert(reasons, "Hooked: " .. v)
            end
        end
    
        if not Security._checkMetamethods() then
            allClean = false
            Security._recordViolation("metamethod_hooked", "Game metamethods tampered")
            table.insert(reasons, "Metamethod hook detected")
        end
    
        return allClean, reasons
    end
    
    -- ============================================
    -- HEARTBEAT (lighter for free)
    -- ============================================
    
    function Security.startHeartbeat()
        task.spawn(function()
            task.wait(math.random(30, 60))
    
            while true do
                task.wait(math.random(45, 120))
    
                pcall(function()
                    if getgenv and getgenv().NexusShuttingDown then return end
                end)
    
                local clean, reasons = Security.runFullScan()
                if not clean and not _degraded then
                    _silentDegrade(table.concat(reasons, "; "))
                end
            end
        end)
    end
    
    -- ============================================
    -- SAFE REQUEST FUNCTION
    -- ============================================
    
    function Security.getSafeRequestFunction()
        local reqFunc = nil
    
        pcall(function()
            if getgenv then
                local env = getgenv()
                reqFunc = env[_STR.request] or env[_STR.http_request]
            end
        end)
    
        if not reqFunc then
            reqFunc = request or http_request or (syn and syn.request) or (http and http.request)
        end
    
        if reqFunc and _isHooked(reqFunc) then
            Security._recordViolation("hooked_request", "HTTP request function hooked")
            local fallbacks = { request, http_request, syn and syn.request, http and http.request }
            for _, fb in ipairs(fallbacks) do
                if fb and not _isHooked(fb) then return fb end
            end
            _silentDegrade("All HTTP functions hooked")
            return nil
        end
    
        return reqFunc
    end
    
    -- ============================================
    -- INIT
    -- ============================================
    
    function Security.init(utilsModule)
        Utils = utilsModule
    
        local clean, reasons = Security.runFullScan()
        if clean then
            print("[Nexus-Security] [+] Initial scan: CLEAN")
        else
            print("[Nexus-Security] [!] Initial scan: " .. #reasons .. " issue(s)")
        end
    
        return clean
    end
    
    return Security
end

_modules["utils"] = function()
    -- Module: utils | SHA: d46572fe53b674e6
    --[[
        NexusBounty Utilities Module
        Encryption, HTTP, HWID, Persistent Storage, Discord Webhook
    ]]
    
    local Utils = {}
    
    -- Services
    local HttpService = game:GetService("HttpService")
    local Players = game:GetService("Players")
    local UserInputService = game:GetService("UserInputService")
    local TweenService = game:GetService("TweenService")
    local GuiService = game:GetService("GuiService")
    
    local lp = Players.LocalPlayer
    
    -- ============================================
    -- ORGANIZED WORKSPACE FOLDER STRUCTURE
    -- ============================================
    -- Nexus/
    -- ├── Data/           (.nxs key and stats files)
    -- ├── Assets/
    -- │   ├── Images/     (logo, icons)
    -- │   └── Sounds/     (bankai.mp3, etc.)
    -- └── Bin/            (reserved for scripts)
    
    Utils.ROOT_FOLDER = "Nexus"
    Utils.DATA_FOLDER = "Nexus/Data"
    Utils.IMAGES_FOLDER = "Nexus/Assets/Images"
    Utils.SOUNDS_FOLDER = "Nexus/Assets/Sounds"
    
    -- Constants
    Utils.API_BASE = "https://keyserver.nexusdevs.fun"
    Utils.KEY_FILE = "Nexus/Data/NexusBounty.nxs"
    Utils.STATS_FILE = "Nexus/Data/NexusBounty_Stats.nxs"
    Utils.CLIENT_VERSION = "6.6"
    Utils.AUTH_URL = Utils.API_BASE -- Alias used by debug share UI
    
    -- Stats persistence config
    Utils.SAVE_INTERVAL = 10 -- Save to disk every 10 seconds max
    Utils._statsLastSaved = 0
    Utils._statsDirty = false
    Utils._statsCache = nil
    
    -- HTTP POST helper (works across executors)
    function Utils.httpPost(url, body, headers)
        headers = headers or {}
        headers["Content-Type"] = headers["Content-Type"] or "application/json"
    
        local requestFn = request or http_request or (http and http.request) or (syn and syn.request)
    
        if requestFn then
            local ok, response = pcall(requestFn, {
                Url = url,
                Method = "POST",
                Headers = headers,
                Body = (type(body) == "string") and body or HttpService:JSONEncode(body),
            })
            if ok and response then
                return response
            end
        end
    
        -- Fallback: try HttpService:RequestAsync
        local ok2, response2 = pcall(function()
            return HttpService:RequestAsync({
                Url = url,
                Method = "POST",
                Headers = headers,
                Body = (type(body) == "string") and body or HttpService:JSONEncode(body),
            })
        end)
        if ok2 and response2 then
            return response2
        end
    
        return nil
    end
    
    Utils.BANKAI_FILE = "Nexus/Assets/Sounds/bankai.mp3"
    Utils.LOGO_FILE = "Nexus/Assets/Images/NexusLogo.png"
    Utils.BANKAI_URL = "https://raw.githubusercontent.com/Ryu-Dev-here/assetsfora/main/bankai.mp3"
    Utils.LOGO_URL = "https://nexusdevs.fun/assets/logos/nexus_dark.webp"
    
    -- Stats caching to reduce file I/O
    Utils._statsCache = nil
    Utils._statsLastSaved = 0
    Utils._statsDirty = false
    Utils.SAVE_INTERVAL = 10 -- seconds between auto-saves
    
    -- Sound state
    Utils._bankaiSound = nil
    
    -- Initialize workspace folders
    function Utils.initFolders()
        pcall(function()
            local makefolder = makefolder or function() end
            local isfolder = isfolder or function() return false end
    
            -- Create folder structure
            local folders = {
                Utils.ROOT_FOLDER,
                Utils.DATA_FOLDER,
                "Nexus/Assets",
                Utils.IMAGES_FOLDER,
                Utils.SOUNDS_FOLDER
            }
    
            for _, folder in ipairs(folders) do
                if not isfolder(folder) then
                    makefolder(folder)
                end
            end
    
            print("[NexusBounty] [+] Workspace folders initialized")
        end)
    end
    
    -- Call init on module load
    Utils.initFolders()
    
    -- Encryption key
    local ENCRYPT_KEY = "45b090e9af3bd54b67216a6d6a8e40bf66eba58cb4adc4286d97ff92137d1bdf"
    
    -- NXS v2 File Format Constants
    local NXS_HEADER = "NXS"
    local NXS_VERSION = 2
    local NXS_SEPARATOR = "|"
    
    -- ============================================
    -- FNV-1a CHECKSUM (32-bit)
    -- ============================================
    
    local FNV_OFFSET = 2166136261
    local FNV_PRIME = 16777619
    
    local function fnv1aHash(data)
        local hash = FNV_OFFSET
        for i = 1, #data do
            hash = bit32.bxor(hash, data:byte(i))
            hash = bit32.band(hash * FNV_PRIME, 0xFFFFFFFF)
        end
        return string.format("%08X", hash)
    end
    
    -- ============================================
    -- SIMPLE XOR ENCRYPTION
    -- ============================================
    
    local function xorEncrypt(data, key)
        local result = {}
        for i = 1, #data do
            local keyChar = key:byte(((i - 1) % #key) + 1)
            local dataChar = data:byte(i)
            table.insert(result, string.char(bit32.bxor(dataChar, keyChar)))
        end
        return table.concat(result)
    end
    
    local function toHex(str)
        local hex = {}
        for i = 1, #str do
            table.insert(hex, string.format("%02x", str:byte(i)))
        end
        return table.concat(hex)
    end
    
    local function fromHex(hexStr)
        local result = {}
        for i = 1, #hexStr, 2 do
            local byte = tonumber(hexStr:sub(i, i + 1), 16)
            if byte then
                table.insert(result, string.char(byte))
            end
        end
        return table.concat(result)
    end
    
    function Utils.encrypt(data)
        local encrypted = xorEncrypt(data, ENCRYPT_KEY)
        return toHex(encrypted)
    end
    
    function Utils.decrypt(hexData)
        local encrypted = fromHex(hexData)
        return xorEncrypt(encrypted, ENCRYPT_KEY)
    end
    
    -- ============================================
    -- NXS v2 FILE FORMAT
    -- Format: NXS|VERSION|CHECKSUM|ENCRYPTED_DATA
    -- ============================================
    
    function Utils.encryptNXSv2(data)
        local encrypted = Utils.encrypt(data)
        local checksum = fnv1aHash(data)
        return NXS_HEADER ..
            NXS_SEPARATOR .. tostring(NXS_VERSION) .. NXS_SEPARATOR .. checksum .. NXS_SEPARATOR .. encrypted
    end
    
    function Utils.decryptNXSv2(content)
        if not content or content == "" then
            return nil, "Empty content"
        end
    
        -- Check if it's NXS v2 format
        if content:sub(1, 4) == NXS_HEADER .. NXS_SEPARATOR then
            local parts = {}
            for part in content:gmatch("([^" .. NXS_SEPARATOR .. "]+)") do
                table.insert(parts, part)
            end
    
            if #parts >= 4 then
                local version = tonumber(parts[2])
                local storedChecksum = parts[3]
                local encryptedData = parts[4]
    
                -- Decrypt
                local decrypted = Utils.decrypt(encryptedData)
                if not decrypted then
                    return nil, "Decryption failed"
                end
    
             
